import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getApp } from "firebase/app";
import { Button, Heading, Wrap } from "@chakra-ui/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log(getApp());

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Wrap>
          <Heading>Hello World</Heading>
          <Button>
            <Link href={"/signup"}>Signup</Link>
          </Button>
        </Wrap>
      </main>
    </>
  );
}
